menu:

- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}


social:
- {icon: 'github', link: 'https://github.com/TY-LOVE-FSY'}
- {icon: 'twitter', link: 'https://twitter.com/Ye26041279'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/yt-love-fsy'}

contacts:
- {name: 'YE TIAN', department: 'Department of Statistics', institution: 'Rutgers-New Brunswick', institution_address: '110 Frelinghuysen Road, Piscataway, NJ 08854', phone: '(732) 689-3031', email: 'yt334@stat.rutgers.edu', office: 'Hill Center 557', image: 'assets/img/ML.jpg'}
